#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include


/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button_kart_click( wxCommandEvent& event );
		void m_button_biegun_click( wxCommandEvent& event );
		void m_checkBoxDot_check( wxCommandEvent& event );
		void m_checkBoxLine_check( wxCommandEvent& event );
		void m_checkBoxAnimuj_clicked( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
	private:
		bool m_uklad_kart = true;

		void Repaint();

};

#endif // __GUIMyFrame1__
